import Footer from '@/components/Footer/Footer'
import { TailwindIndicator } from '@/components/dev/TailwindIndicator'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { item: string }
}) {
  
  return (
    <html lang='en'>
      <body className={montserrat.className}>
        {/* <Header /> */}
        <main className='page'>{children}</main>
        <TailwindIndicator />
        <Footer />
      </body>
    </html>
  )
}
