import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'
import { TailwindIndicator } from '@/components/dev/TailwindIndicator'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={montserrat.className}>
        <Header />
        {children}
        <TailwindIndicator />
        <Footer />
      </body>
    </html>
  )
}
