import Footer from '@/components/Footer/Footer'
import { TailwindIndicator } from '@/components/dev/TailwindIndicator'
import { cn } from '@/utils'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={cn(montserrat.className, 'flex flex-col justify-between')}
      >
        {/* <Header /> */}
        {children}
        <TailwindIndicator />
        {/* <Footer /> */}
      </body>
    </html>
  )
}
